package com.codeborne.geoip;

@SuppressWarnings("OverlyLongMethod")
public final class timeZone {
  public static String timeZoneByCountryAndRegion(String country, String region) {
    if (country == null) {
      return null;
    }
    if (region == null) {
      region = "";
    }
    switch (country) {
      case "AD":
        return "Europe/Andorra";
      case "AE":
        return "Asia/Dubai";
      case "AF":
        return "Asia/Kabul";
      case "AG":
        return "America/Antigua";
      case "AI":
        return "America/Anguilla";
      case "AL":
        return "Europe/Tirane";
      case "AM":
        return "Asia/Yerevan";
      case "AN":
        return "America/Curacao";
      case "AO":
        return "Africa/Luanda";
      case "AQ":
        return "Antarctica/South_Pole";
      case "AR":
        return argentina(region);
      case "AS":
        return "Pacific/Pago_Pago";
      case "AT":
        return "Europe/Vienna";
      case "AU":
        return australia(region);
      case "AW":
        return "America/Aruba";
      case "AX":
        return "Europe/Mariehamn";
      case "AZ":
        return "Asia/Baku";
      case "BA":
        return "Europe/Sarajevo";
      case "BB":
        return "America/Barbados";
      case "BD":
        return "Asia/Dhaka";
      case "BE":
        return "Europe/Brussels";
      case "BF":
        return "Africa/Ouagadougou";
      case "BG":
        return "Europe/Sofia";
      case "BH":
        return "Asia/Bahrain";
      case "BI":
        return "Africa/Bujumbura";
      case "BJ":
        return "Africa/Porto-Novo";
      case "BM":
        return "Atlantic/Bermuda";
      case "BN":
        return "Asia/Brunei";
      case "BO":
        return "America/La_Paz";
      case "BR":
        return brasilia(region);
      case "BS":
        return "America/Nassau";
      case "BT":
        return "Asia/Thimphu";
      case "BV":
        return "Antarctica/Syowa";
      case "BW":
        return "Africa/Gaborone";
      case "BY":
        return "Europe/Minsk";
      case "BZ":
        return "America/Belize";
      case "CA":
        return canada(region);
      case "CC":
        return "Indian/Cocos";
      case "CD":
        return congo(region);
      case "CF":
        return "Africa/Bangui";
      case "CG":
        return "Africa/Brazzaville";
      case "CH":
        return "Europe/Zurich";
      case "CI":
        return "Africa/Abidjan";
      case "CK":
        return "Pacific/Rarotonga";
      case "CL":
        return "America/Santiago";
      case "CM":
        return "Africa/Douala";
      case "CN":
        return china(region);
      case "CO":
        return "America/Bogota";
      case "CR":
        return "America/Costa_Rica";
      case "CU":
        return "America/Havana";
      case "CV":
        return "Atlantic/Cape_Verde";
      case "CX":
        return "Indian/Christmas";
      case "CY":
        return "Asia/Nicosia";
      case "CZ":
        return "Europe/Prague";
      case "DE":
        return "Europe/Berlin";
      case "DJ":
        return "Africa/Djibouti";
      case "DK":
        return "Europe/Copenhagen";
      case "DM":
        return "America/Dominica";
      case "DO":
        return "America/Santo_Domingo";
      case "DZ":
        return "Africa/Algiers";
      case "EC":
        return ecuador(region);
      case "EE":
        return "Europe/Tallinn";
      case "EG":
        return "Africa/Cairo";
      case "EH":
        return "Africa/El_Aaiun";
      case "ER":
        return "Africa/Asmara";
      case "ES":
        return spain(region);
      case "ET":
        return "Africa/Addis_Ababa";
      case "FI":
        return "Europe/Helsinki";
      case "FJ":
        return "Pacific/Fiji";
      case "FK":
        return "Atlantic/Stanley";
      case "FM":
        return "Pacific/Pohnpei";
      case "FO":
        return "Atlantic/Faroe";
      case "FR":
        return "Europe/Paris";
      case "GA":
        return "Africa/Libreville";
      case "GB":
        return "Europe/London";
      case "GD":
        return "America/Grenada";
      case "GE":
        return "Asia/Tbilisi";
      case "GF":
        return "America/Cayenne";
      case "GG":
        return "Europe/Guernsey";
      case "GH":
        return "Africa/Accra";
      case "GI":
        return "Europe/Gibraltar";
      case "GL":
        return greenland(region);
      case "GM":
        return "Africa/Banjul";
      case "GN":
        return "Africa/Conakry";
      case "GP":
        return "America/Guadeloupe";
      case "GQ":
        return "Africa/Malabo";
      case "GR":
        return "Europe/Athens";
      case "GS":
        return "Atlantic/South_Georgia";
      case "GT":
        return "America/Guatemala";
      case "GU":
        return "Pacific/Guam";
      case "GW":
        return "Africa/Bissau";
      case "GY":
        return "America/Guyana";
      case "HK":
        return "Asia/Hong_Kong";
      case "HN":
        return "America/Tegucigalpa";
      case "HR":
        return "Europe/Zagreb";
      case "HT":
        return "America/Port-au-Prince";
      case "HU":
        return "Europe/Budapest";
      case "ID":
        return indonesia(region);
      case "IE":
        return "Europe/Dublin";
      case "IL":
        return "Asia/Jerusalem";
      case "IM":
        return "Europe/Isle_of_Man";
      case "IN":
        return "Asia/Kolkata";
      case "IO":
        return "Indian/Chagos";
      case "IQ":
        return "Asia/Baghdad";
      case "IR":
        return "Asia/Tehran";
      case "IS":
        return "Atlantic/Reykjavik";
      case "IT":
        return "Europe/Rome";
      case "JE":
        return "Europe/Jersey";
      case "JM":
        return "America/Jamaica";
      case "JO":
        return "Asia/Amman";
      case "JP":
        return "Asia/Tokyo";
      case "KE":
        return "Africa/Nairobi";
      case "KG":
        return "Asia/Bishkek";
      case "KH":
        return "Asia/Phnom_Penh";
      case "KI":
        return "Pacific/Tarawa";
      case "KM":
        return "Indian/Comoro";
      case "KN":
        return "America/St_Kitts";
      case "KP":
        return "Asia/Pyongyang";
      case "KR":
        return "Asia/Seoul";
      case "KW":
        return "Asia/Kuwait";
      case "KY":
        return "America/Cayman";
      case "KZ":
        return kazakhstan(region);
      case "LA":
        return "Asia/Vientiane";
      case "LB":
        return "Asia/Beirut";
      case "LC":
        return "America/St_Lucia";
      case "LI":
        return "Europe/Vaduz";
      case "LK":
        return "Asia/Colombo";
      case "LR":
        return "Africa/Monrovia";
      case "LS":
        return "Africa/Maseru";
      case "LT":
        return "Europe/Vilnius";
      case "LU":
        return "Europe/Luxembourg";
      case "LV":
        return "Europe/Riga";
      case "LY":
        return "Africa/Tripoli";
      case "MA":
        return "Africa/Casablanca";
      case "MC":
        return "Europe/Monaco";
      case "MD":
        return "Europe/Chisinau";
      case "ME":
        return "Europe/Podgorica";
      case "MG":
        return "Indian/Antananarivo";
      case "MH":
        return "Pacific/Kwajalein";
      case "MK":
        return "Europe/Skopje";
      case "ML":
        return "Africa/Bamako";
      case "MM":
        return "Asia/Rangoon";
      case "MN":
        return mongolia(region);
      case "MO":
        return "Asia/Macau";
      case "MP":
        return "Pacific/Saipan";
      case "MQ":
        return "America/Martinique";
      case "MR":
        return "Africa/Nouakchott";
      case "MS":
        return "America/Montserrat";
      case "MT":
        return "Europe/Malta";
      case "MU":
        return "Indian/Mauritius";
      case "MV":
        return "Indian/Maldives";
      case "MW":
        return "Africa/Blantyre";
      case "MX":
        return mexico(region);
      case "MY":
        return malaysia(region);
      case "MZ":
        return "Africa/Maputo";
      case "NA":
        return "Africa/Windhoek";
      case "NC":
        return "Pacific/Noumea";
      case "NE":
        return "Africa/Niamey";
      case "NF":
        return "Pacific/Norfolk";
      case "NG":
        return "Africa/Lagos";
      case "NI":
        return "America/Managua";
      case "NL":
        return "Europe/Amsterdam";
      case "NO":
        return "Europe/Oslo";
      case "NP":
        return "Asia/Kathmandu";
      case "NR":
        return "Pacific/Nauru";
      case "NU":
        return "Pacific/Niue";
      case "NZ":
        return newZealand(region);
      case "OM":
        return "Asia/Muscat";
      case "PA":
        return "America/Panama";
      case "PE":
        return "America/Lima";
      case "PF":
        return "Pacific/Marquesas";
      case "PG":
        return "Pacific/Port_Moresby";
      case "PH":
        return "Asia/Manila";
      case "PK":
        return "Asia/Karachi";
      case "PL":
        return "Europe/Warsaw";
      case "PM":
        return "America/Miquelon";
      case "PR":
        return "America/Puerto_Rico";
      case "PS":
        return "Asia/Gaza";
      case "PT":
        return portugal(region);
      case "PW":
        return "Pacific/Palau";
      case "PY":
        return "America/Asuncion";
      case "QA":
        return "Asia/Qatar";
      case "RE":
        return "Indian/Reunion";
      case "RO":
        return "Europe/Bucharest";
      case "RS":
        return "Europe/Belgrade";
      case "RU":
        return russia(region);
      case "RW":
        return "Africa/Kigali";
      case "SA":
        return "Asia/Riyadh";
      case "SB":
        return "Pacific/Guadalcanal";
      case "SC":
        return "Indian/Mahe";
      case "SD":
        return "Africa/Khartoum";
      case "SE":
        return "Europe/Stockholm";
      case "SG":
        return "Asia/Singapore";
      case "SH":
        return "Atlantic/St_Helena";
      case "SI":
        return "Europe/Ljubljana";
      case "SJ":
        return "Arctic/Longyearbyen";
      case "SK":
        return "Europe/Bratislava";
      case "SL":
        return "Africa/Freetown";
      case "SM":
        return "Europe/San_Marino";
      case "SN":
        return "Africa/Dakar";
      case "SO":
        return "Africa/Mogadishu";
      case "SR":
        return "America/Paramaribo";
      case "ST":
        return "Africa/Sao_Tome";
      case "SV":
        return "America/El_Salvador";
      case "SY":
        return "Asia/Damascus";
      case "SZ":
        return "Africa/Mbabane";
      case "TC":
        return "America/Grand_Turk";
      case "TD":
        return "Africa/Ndjamena";
      case "TF":
        return "Indian/Kerguelen";
      case "TG":
        return "Africa/Lome";
      case "TH":
        return "Asia/Bangkok";
      case "TJ":
        return "Asia/Dushanbe";
      case "TK":
        return "Pacific/Fakaofo";
      case "TL":
        return "Asia/Dili";
      case "TM":
        return "Asia/Ashgabat";
      case "TN":
        return "Africa/Tunis";
      case "TO":
        return "Pacific/Tongatapu";
      case "TR":
        return "Europe/Istanbul";
      case "TT":
        return "America/Port_of_Spain";
      case "TV":
        return "Pacific/Funafuti";
      case "TW":
        return "Asia/Taipei";
      case "TZ":
        return "Africa/Dar_es_Salaam";
      case "UA":
        return ukraine(region);
      case "UG":
        return "Africa/Kampala";
      case "UM":
        return "Pacific/Wake";
      case "US":
        return usa(region);
      case "UY":
        return "America/Montevideo";
      case "UZ":
        return uzbekistan(region);
      case "VA":
        return "Europe/Vatican";
      case "VC":
        return "America/St_Vincent";
      case "VE":
        return "America/Caracas";
      case "VG":
        return "America/Tortola";
      case "VI":
        return "America/St_Thomas";
      case "VN":
        return "Asia/Ho_Chi_Minh";
      case "VU":
        return "Pacific/Efate";
      case "WF":
        return "Pacific/Wallis";
      case "WS":
        return "Pacific/Apia";
      case "YE":
        return "Asia/Aden";
      case "YT":
        return "Indian/Mayotte";
      case "ZA":
        return "Africa/Johannesburg";
      case "ZM":
        return "Africa/Lusaka";
      case "ZW":
        return "Africa/Harare";
      case "SX":
        return "America/Curacao";
      case "BQ":
        return "America/Curacao";
      case "CW":
        return "America/Curacao";
      case "BL":
        return "America/St_Barthelemy";
      case "PN":
        return "Pacific/Pitcairn";
    }
    return null;
  }

  private static String uzbekistan(String region) {
    switch (region) {
      case "01":
        return "Asia/Tashkent";
      case "02":
        return "Asia/Samarkand";
      case "03":
        return "Asia/Tashkent";
      case "05":
        return "Asia/Samarkand";
      case "06":
        return "Asia/Tashkent";
      case "07":
        return "Asia/Samarkand";
      case "08":
        return "Asia/Samarkand";
      case "10":
        return "Asia/Samarkand";
      case "12":
        return "Asia/Samarkand";
      case "13":
        return "Asia/Tashkent";
      case "14":
        return "Asia/Tashkent";
      default:
        return "Asia/Uzbekistan";
    }
  }

  private static String usa(String region) {
    switch (region) {
      case "AK":
        return "America/Anchorage";
      case "AL":
        return "America/Chicago";
      case "AR":
        return "America/Chicago";
      case "AZ":
        return "America/Phoenix";
      case "CA":
        return "America/Los_Angeles";
      case "CO":
        return "America/Denver";
      case "CT":
        return "America/New_York";
      case "DC":
        return "America/New_York";
      case "DE":
        return "America/New_York";
      case "FL":
        return "America/New_York";
      case "GA":
        return "America/New_York";
      case "HI":
        return "Pacific/Honolulu";
      case "IA":
        return "America/Chicago";
      case "ID":
        return "America/Denver";
      case "IL":
        return "America/Chicago";
      case "IN":
        return "America/Indianapolis";
      case "KS":
        return "America/Chicago";
      case "KY":
        return "America/New_York";
      case "LA":
        return "America/Chicago";
      case "MA":
        return "America/New_York";
      case "MD":
        return "America/New_York";
      case "ME":
        return "America/New_York";
      case "MI":
        return "America/New_York";
      case "MN":
        return "America/Chicago";
      case "MO":
        return "America/Chicago";
      case "MS":
        return "America/Chicago";
      case "MT":
        return "America/Denver";
      case "NC":
        return "America/New_York";
      case "ND":
        return "America/Chicago";
      case "NE":
        return "America/Chicago";
      case "NH":
        return "America/New_York";
      case "NJ":
        return "America/New_York";
      case "NM":
        return "America/Denver";
      case "NV":
        return "America/Los_Angeles";
      case "NY":
        return "America/New_York";
      case "OH":
        return "America/New_York";
      case "OK":
        return "America/Chicago";
      case "OR":
        return "America/Los_Angeles";
      case "PA":
        return "America/New_York";
      case "RI":
        return "America/New_York";
      case "SC":
        return "America/New_York";
      case "SD":
        return "America/Chicago";
      case "TN":
        return "America/Chicago";
      case "TX":
        return "America/Chicago";
      case "UT":
        return "America/Denver";
      case "VA":
        return "America/New_York";
      case "VT":
        return "America/New_York";
      case "WA":
        return "America/Los_Angeles";
      case "WI":
        return "America/Chicago";
      case "WV":
        return "America/New_York";
      case "WY":
        return "America/Denver";
      default:
        return "America/USA";
    }
  }

  private static String ukraine(String region) {
    switch (region) {
      case "01":
        return "Europe/Kiev";
      case "02":
        return "Europe/Kiev";
      case "03":
        return "Europe/Uzhgorod";
      case "04":
        return "Europe/Zaporozhye";
      case "05":
        return "Europe/Zaporozhye";
      case "06":
        return "Europe/Uzhgorod";
      case "07":
        return "Europe/Zaporozhye";
      case "08":
        return "Europe/Simferopol";
      case "09":
        return "Europe/Kiev";
      case "10":
        return "Europe/Zaporozhye";
      case "11":
        return "Europe/Simferopol";
      case "12":
        return "Europe/Kiev";
      case "13":
        return "Europe/Kiev";
      case "14":
        return "Europe/Zaporozhye";
      case "15":
        return "Europe/Uzhgorod";
      case "16":
        return "Europe/Zaporozhye";
      case "17":
        return "Europe/Simferopol";
      case "18":
        return "Europe/Zaporozhye";
      case "19":
        return "Europe/Kiev";
      case "20":
        return "Europe/Simferopol";
      case "21":
        return "Europe/Kiev";
      case "22":
        return "Europe/Uzhgorod";
      case "23":
        return "Europe/Kiev";
      case "24":
        return "Europe/Uzhgorod";
      case "25":
        return "Europe/Uzhgorod";
      case "26":
        return "Europe/Zaporozhye";
      case "27":
        return "Europe/Kiev";
      default:
        return "Europe/Ukraine";
    }
  }

  private static String russia(String region) {
    switch (region) {
      case "01":
        return "Europe/Volgograd";
      case "02":
        return "Asia/Irkutsk";
      case "03":
        return "Asia/Novokuznetsk";
      case "04":
        return "Asia/Novosibirsk";
      case "05":
        return "Asia/Vladivostok";
      case "06":
        return "Europe/Moscow";
      case "07":
        return "Europe/Volgograd";
      case "08":
        return "Europe/Samara";
      case "09":
        return "Europe/Volgograd";
      case "10":
        return "Europe/Moscow";
      case "11":
        return "Asia/Irkutsk";
      case "12":
        return "Europe/Volgograd";
      case "13":
        return "Asia/Yekaterinburg";
      case "14":
        return "Asia/Irkutsk";
      case "15":
        return "Asia/Anadyr";
      case "16":
        return "Europe/Samara";
      case "17":
        return "Europe/Volgograd";
      case "18":
        return "Asia/Krasnoyarsk";
      case "20":
        return "Asia/Irkutsk";
      case "21":
        return "Europe/Moscow";
      case "22":
        return "Europe/Volgograd";
      case "23":
        return "Europe/Kaliningrad";
      case "24":
        return "Europe/Volgograd";
      case "25":
        return "Europe/Moscow";
      case "26":
        return "Asia/Kamchatka";
      case "27":
        return "Europe/Volgograd";
      case "28":
        return "Europe/Moscow";
      case "29":
        return "Asia/Novokuznetsk";
      case "30":
        return "Asia/Sakhalin";
      case "31":
        return "Asia/Krasnoyarsk";
      case "32":
        return "Asia/Yekaterinburg";
      case "33":
        return "Europe/Samara";
      case "34":
        return "Asia/Yekaterinburg";
      case "36":
        return "Asia/Anadyr";
      case "37":
        return "Europe/Moscow";
      case "38":
        return "Europe/Volgograd";
      case "39":
        return "Asia/Krasnoyarsk";
      case "40":
        return "Asia/Yekaterinburg";
      case "41":
        return "Europe/Moscow";
      case "42":
        return "Europe/Moscow";
      case "43":
        return "Europe/Moscow";
      case "44":
        return "Asia/Magadan";
      case "45":
        return "Europe/Samara";
      case "46":
        return "Europe/Samara";
      case "47":
        return "Europe/Moscow";
      case "48":
        return "Europe/Moscow";
      case "49":
        return "Europe/Moscow";
      case "50":
        return "Asia/Yekaterinburg";
      case "51":
        return "Europe/Moscow";
      case "52":
        return "Europe/Moscow";
      case "53":
        return "Asia/Novosibirsk";
      case "54":
        return "Asia/Omsk";
      case "55":
        return "Europe/Samara";
      case "56":
        return "Europe/Moscow";
      case "57":
        return "Europe/Samara";
      case "58":
        return "Asia/Yekaterinburg";
      case "59":
        return "Asia/Vladivostok";
      case "60":
        return "Europe/Moscow";
      case "61":
        return "Europe/Volgograd";
      case "62":
        return "Europe/Moscow";
      case "63":
        return "Asia/Yakutsk";
      case "64":
        return "Asia/Sakhalin";
      case "65":
        return "Europe/Samara";
      case "66":
        return "Europe/Moscow";
      case "67":
        return "Europe/Samara";
      case "68":
        return "Europe/Volgograd";
      case "69":
        return "Europe/Moscow";
      case "70":
        return "Europe/Volgograd";
      case "71":
        return "Asia/Yekaterinburg";
      case "72":
        return "Europe/Moscow";
      case "73":
        return "Europe/Samara";
      case "74":
        return "Asia/Yakutsk";
      case "75":
        return "Asia/Novosibirsk";
      case "76":
        return "Europe/Moscow";
      case "77":
        return "Europe/Moscow";
      case "78":
        return "Asia/Omsk";
      case "79":
        return "Asia/Irkutsk";
      case "80":
        return "Asia/Yekaterinburg";
      case "81":
        return "Europe/Samara";
      case "83":
        return "Europe/Moscow";
      case "84":
        return "Europe/Volgograd";
      case "85":
        return "Europe/Moscow";
      case "86":
        return "Europe/Volgograd";
      case "87":
        return "Asia/Omsk";
      case "88":
        return "Europe/Moscow";
      case "89":
        return "Asia/Vladivostok";
      case "90":
        return "Asia/Yekaterinburg";
      case "91":
        return "Asia/Krasnoyarsk";
      case "92":
        return "Asia/Anadyr";
      case "93":
        return "Asia/Irkutsk";
      case "CI":
        return "Europe/Volgograd";
      case "JA":
        return "Asia/Sakhalin";
      default:
        return "Russia";
    }
  }

  private static String portugal(String region) {
    switch (region) {
      case "02":
        return "Europe/Lisbon";
      case "03":
        return "Europe/Lisbon";
      case "04":
        return "Europe/Lisbon";
      case "05":
        return "Europe/Lisbon";
      case "06":
        return "Europe/Lisbon";
      case "07":
        return "Europe/Lisbon";
      case "08":
        return "Europe/Lisbon";
      case "09":
        return "Europe/Lisbon";
      case "10":
        return "Atlantic/Madeira";
      case "11":
        return "Europe/Lisbon";
      case "13":
        return "Europe/Lisbon";
      case "14":
        return "Europe/Lisbon";
      case "16":
        return "Europe/Lisbon";
      case "17":
        return "Europe/Lisbon";
      case "18":
        return "Europe/Lisbon";
      case "19":
        return "Europe/Lisbon";
      case "20":
        return "Europe/Lisbon";
      case "21":
        return "Europe/Lisbon";
      case "22":
        return "Europe/Lisbon";
      case "23":
        return "Atlantic/Azores";
      default:
        return "Atlantic/Portugal";
    }
  }

  private static String newZealand(String region) {
    switch (region) {
      case "E7":
        return "Pacific/Auckland";
      case "E8":
        return "Pacific/Auckland";
      case "E9":
        return "Pacific/Auckland";
      case "F1":
        return "Pacific/Auckland";
      case "F2":
        return "Pacific/Auckland";
      case "F3":
        return "Pacific/Auckland";
      case "F4":
        return "Pacific/Auckland";
      case "F5":
        return "Pacific/Auckland";
      case "F6":
        return "Pacific/Auckland";
      case "F7":
        return "Pacific/Chatham";
      case "F8":
        return "Pacific/Auckland";
      case "F9":
        return "Pacific/Auckland";
      case "G1":
        return "Pacific/Auckland";
      case "G2":
        return "Pacific/Auckland";
      case "G3":
        return "Pacific/Auckland";
      default:
        return "Pacific/New-Zealand";
    }
  }

  private static String malaysia(String region) {
    switch (region) {
      case "01":
        return "Asia/Kuala_Lumpur";
      case "02":
        return "Asia/Kuala_Lumpur";
      case "03":
        return "Asia/Kuala_Lumpur";
      case "04":
        return "Asia/Kuala_Lumpur";
      case "05":
        return "Asia/Kuala_Lumpur";
      case "06":
        return "Asia/Kuala_Lumpur";
      case "07":
        return "Asia/Kuala_Lumpur";
      case "08":
        return "Asia/Kuala_Lumpur";
      case "09":
        return "Asia/Kuala_Lumpur";
      case "11":
        return "Asia/Kuching";
      case "12":
        return "Asia/Kuala_Lumpur";
      case "13":
        return "Asia/Kuala_Lumpur";
      case "14":
        return "Asia/Kuala_Lumpur";
      case "15":
        return "Asia/Kuching";
      case "16":
        return "Asia/Kuching";
      default:
        return "Asia/Malaysia";
    }
  }

  private static String mexico(String region) {
    switch (region) {
      case "01":
        return "America/Bahia_Banderas";
      case "02":
        return "America/Tijuana";
      case "03":
        return "America/Mazatlan";
      case "04":
        return "America/Merida";
      case "05":
        return "America/Merida";
      case "06":
        return "America/Chihuahua";
      case "07":
        return "America/Monterrey";
      case "08":
        return "America/Bahia_Banderas";
      case "09":
        return "America/Mexico_City";
      case "10":
        return "America/Mazatlan";
      case "11":
        return "America/Mexico_City";
      case "12":
        return "America/Mexico_City";
      case "13":
        return "America/Mexico_City";
      case "14":
        return "America/Bahia_Banderas";
      case "15":
        return "America/Mexico_City";
      case "16":
        return "America/Mexico_City";
      case "17":
        return "America/Mexico_City";
      case "18":
        return "America/Bahia_Banderas";
      case "19":
        return "America/Monterrey";
      case "20":
        return "America/Mexico_City";
      case "21":
        return "America/Mexico_City";
      case "22":
        return "America/Mexico_City";
      case "23":
        return "America/Cancun";
      case "24":
        return "America/Mexico_City";
      case "25":
        return "America/Mazatlan";
      case "26":
        return "America/Hermosillo";
      case "27":
        return "America/Merida";
      case "28":
        return "America/Matamoros";
      case "29":
        return "America/Mexico_City";
      case "30":
        return "America/Mexico_City";
      case "31":
        return "America/Merida";
      case "32":
        return "America/Bahia_Banderas";
      default:
        return "America/Mexico";
    }
  }

  private static String mongolia(String region) {
    switch (region) {
      case "06":
        return "Asia/Choibalsan";
      case "11":
        return "Asia/Ulaanbaatar";
      case "17":
        return "Asia/Choibalsan";
      case "19":
        return "Asia/Hovd";
      case "20":
        return "Asia/Ulaanbaatar";
      case "21":
        return "Asia/Ulaanbaatar";
      case "25":
        return "Asia/Ulaanbaatar";
      default:
        return "Asia/Mongolia";
    }
  }

  private static String kazakhstan(String region) {
    switch (region) {
      case "01":
        return "Asia/Almaty";
      case "02":
        return "Asia/Almaty";
      case "03":
        return "Asia/Qyzylorda";
      case "04":
        return "Asia/Aqtobe";
      case "05":
        return "Asia/Qyzylorda";
      case "06":
        return "Asia/Aqtau";
      case "07":
        return "Asia/Oral";
      case "08":
        return "Asia/Qyzylorda";
      case "09":
        return "Asia/Aqtau";
      case "10":
        return "Asia/Qyzylorda";
      case "11":
        return "Asia/Almaty";
      case "12":
        return "Asia/Almaty";
      case "13":
        return "Asia/Aqtobe";
      case "14":
        return "Asia/Qyzylorda";
      case "15":
        return "Asia/Almaty";
      case "16":
        return "Asia/Aqtobe";
      case "17":
        return "Asia/Almaty";
      default:
        return "Asia/Kazakhstan";
    }
  }

  private static String indonesia(String region) {
    switch (region) {
      case "01":
        return "Asia/Pontianak";
      case "02":
        return "Asia/Makassar";
      case "03":
        return "Asia/Jakarta";
      case "04":
        return "Asia/Jakarta";
      case "05":
        return "Asia/Jakarta";
      case "07":
        return "Asia/Jakarta";
      case "08":
        return "Asia/Jakarta";
      case "10":
        return "Asia/Jakarta";
      case "11":
        return "Asia/Pontianak";
      case "12":
        return "Asia/Makassar";
      case "13":
        return "Asia/Pontianak";
      case "14":
        return "Asia/Makassar";
      case "15":
        return "Asia/Jakarta";
      case "17":
        return "Asia/Makassar";
      case "18":
        return "Asia/Makassar";
      case "21":
        return "Asia/Makassar";
      case "22":
        return "Asia/Makassar";
      case "24":
        return "Asia/Jakarta";
      case "26":
        return "Asia/Pontianak";
      case "28":
        return "Asia/Jayapura";
      case "29":
        return "Asia/Makassar";
      case "30":
        return "Asia/Jakarta";
      case "31":
        return "Asia/Makassar";
      case "32":
        return "Asia/Jakarta";
      case "33":
        return "Asia/Jakarta";
      case "34":
        return "Asia/Makassar";
      case "35":
        return "Asia/Pontianak";
      case "36":
        return "Asia/Jayapura";
      case "37":
        return "Asia/Pontianak";
      case "38":
        return "Asia/Makassar";
      case "39":
        return "Asia/Jayapura";
      case "40":
        return "Asia/Pontianak";
      case "41":
        return "Asia/Makassar";
      default:
        return "Asia/Indonesia";
    }
  }

  private static String greenland(String region) {
    switch (region) {
      case "01":
        return "America/Thule";
      case "02":
        return "America/Scoresbysund";
      case "03":
        return "America/Godthab";
      default:
        return "America/Greenland";
    }
  }

  private static String spain(String region) {
    switch (region) {
      case "07":
        return "Europe/Madrid";
      case "27":
        return "Europe/Madrid";
      case "29":
        return "Europe/Madrid";
      case "31":
        return "Europe/Madrid";
      case "32":
        return "Europe/Madrid";
      case "34":
        return "Europe/Madrid";
      case "39":
        return "Europe/Madrid";
      case "51":
        return "Africa/Ceuta";
      case "52":
        return "Europe/Madrid";
      case "53":
        return "Atlantic/Canary";
      case "54":
        return "Europe/Madrid";
      case "55":
        return "Europe/Madrid";
      case "56":
        return "Europe/Madrid";
      case "57":
        return "Europe/Madrid";
      case "58":
        return "Europe/Madrid";
      case "59":
        return "Europe/Madrid";
      case "60":
        return "Europe/Madrid";
      default:
        return "Europe/Spain";
    }
  }

  private static String ecuador(String region) {
    switch (region) {
      case "01":
        return "Pacific/Galapagos";
      case "02":
        return "America/Guayaquil";
      case "03":
        return "America/Guayaquil";
      case "04":
        return "America/Guayaquil";
      case "05":
        return "America/Guayaquil";
      case "06":
        return "America/Guayaquil";
      case "07":
        return "America/Guayaquil";
      case "08":
        return "America/Guayaquil";
      case "09":
        return "America/Guayaquil";
      case "10":
        return "America/Guayaquil";
      case "11":
        return "America/Guayaquil";
      case "12":
        return "America/Guayaquil";
      case "13":
        return "America/Guayaquil";
      case "14":
        return "America/Guayaquil";
      case "15":
        return "America/Guayaquil";
      case "17":
        return "America/Guayaquil";
      case "18":
        return "America/Guayaquil";
      case "19":
        return "America/Guayaquil";
      case "22":
        return "America/Guayaquil";
      case "24":
        return "America/Guayaquil";
      default:
        return "America/Guayaquil";
    }
  }

  private static String china(String region) {
    switch (region) {
      case "01":
        return "Asia/Shanghai";
      case "02":
        return "Asia/Shanghai";
      case "03":
        return "Asia/Shanghai";
      case "04":
        return "Asia/Shanghai";
      case "05":
        return "Asia/Harbin";
      case "06":
        return "Asia/Chongqing";
      case "07":
        return "Asia/Shanghai";
      case "08":
        return "Asia/Harbin";
      case "09":
        return "Asia/Shanghai";
      case "10":
        return "Asia/Shanghai";
      case "11":
        return "Asia/Chongqing";
      case "12":
        return "Asia/Chongqing";
      case "13":
        return "Asia/Urumqi";
      case "14":
        return "Asia/Chongqing";
      case "15":
        return "Asia/Chongqing";
      case "16":
        return "Asia/Chongqing";
      case "18":
        return "Asia/Chongqing";
      case "19":
        return "Asia/Harbin";
      case "20":
        return "Asia/Harbin";
      case "21":
        return "Asia/Chongqing";
      case "22":
        return "Asia/Harbin";
      case "23":
        return "Asia/Shanghai";
      case "24":
        return "Asia/Chongqing";
      case "25":
        return "Asia/Shanghai";
      case "26":
        return "Asia/Chongqing";
      case "28":
        return "Asia/Shanghai";
      case "29":
        return "Asia/Chongqing";
      case "30":
        return "Asia/Chongqing";
      case "31":
        return "Asia/Chongqing";
      case "32":
        return "Asia/Chongqing";
      case "33":
        return "Asia/Chongqing";
      default:
        return "Asia/China";
    }
  }

  private static String congo(String region) {
    switch (region) {
      case "01":
        return "Africa/Kinshasa";
      case "02":
        return "Africa/Kinshasa";
      case "03":
        return "Africa/Kinshasa";
      case "04":
        return "Africa/Lubumbashi";
      case "05":
        return "Africa/Lubumbashi";
      case "06":
        return "Africa/Kinshasa";
      case "07":
        return "Africa/Lubumbashi";
      case "08":
        return "Africa/Kinshasa";
      case "09":
        return "Africa/Lubumbashi";
      case "10":
        return "Africa/Lubumbashi";
      case "11":
        return "Africa/Lubumbashi";
      case "12":
        return "Africa/Lubumbashi";
      default:
        return "Africa/Congo";
    }
  }

  private static String canada(String region) {
    switch (region) {
      case "AB":
        return "America/Edmonton";
      case "BC":
        return "America/Vancouver";
      case "MB":
        return "America/Winnipeg";
      case "NB":
        return "America/Halifax";
      case "NL":
        return "America/St_Johns";
      case "NS":
        return "America/Halifax";
      case "NT":
        return "America/Yellowknife";
      case "NU":
        return "America/Rankin_Inlet";
      case "ON":
        return "America/Rainy_River";
      case "PE":
        return "America/Halifax";
      case "QC":
        return "America/Montreal";
      case "SK":
        return "America/Regina";
      case "YT":
        return "America/Whitehorse";
      default:
        return "America/Canada";
    }
  }

  private static String brasilia(String region) {
    switch (region) {
      case "01":
        return "America/Rio_Branco";
      case "02":
        return "America/Maceio";
      case "03":
        return "America/Belem";
      case "04":
        return "America/Manaus";
      case "05":
        return "America/Bahia";
      case "06":
        return "America/Fortaleza";
      case "07":
        return "America/Cuiaba";
      case "08":
        return "America/Sao_Paulo";
      case "11":
        return "America/Campo_Grande";
      case "13":
        return "America/Araguaina";
      case "14":
        return "America/Cuiaba";
      case "15":
        return "America/Sao_Paulo";
      case "16":
        return "America/Belem";
      case "17":
        return "America/Recife";
      case "18":
        return "America/Campo_Grande";
      case "20":
        return "America/Fortaleza";
      case "21":
        return "America/Sao_Paulo";
      case "22":
        return "America/Recife";
      case "23":
        return "America/Sao_Paulo";
      case "24":
        return "America/Porto_Velho";
      case "25":
        return "America/Boa_Vista";
      case "26":
        return "America/Sao_Paulo";
      case "27":
        return "America/Sao_Paulo";
      case "28":
        return "America/Maceio";
      case "29":
        return "America/Campo_Grande";
      case "30":
        return "America/Recife";
      case "31":
        return "America/Araguaina";
      default:
        return "America/Brasilia";
    }
  }

  private static String australia(String region) {
    switch (region) {
      case "01":
        return "Australia/Sydney";
      case "02":
        return "Australia/Sydney";
      case "03":
        return "Australia/Darwin";
      case "04":
        return "Australia/Brisbane";
      case "05":
        return "Australia/Adelaide";
      case "06":
        return "Australia/Hobart";
      case "07":
        return "Australia/Melbourne";
      case "08":
        return "Australia/Perth";
      default:
        return "Australia";
    }
  }

  private static String argentina(String region) {
    switch (region) {
      case "01":
        return "America/Argentina/Buenos_Aires";
      case "02":
        return "America/Argentina/Catamarca";
      case "03":
        return "America/Argentina/Tucuman";
      case "04":
        return "America/Argentina/Rio_Gallegos";
      case "05":
        return "America/Argentina/Cordoba";
      case "06":
        return "America/Argentina/Buenos_Aires";
      case "07":
        return "America/Argentina/Buenos_Aires";
      case "08":
        return "America/Argentina/Buenos_Aires";
      case "09":
        return "America/Argentina/Tucuman";
      case "10":
        return "America/Argentina/Jujuy";
      case "11":
        return "America/Argentina/San_Luis";
      case "12":
        return "America/Argentina/La_Rioja";
      case "13":
        return "America/Argentina/Mendoza";
      case "14":
        return "America/Argentina/Buenos_Aires";
      case "15":
        return "America/Argentina/Mendoza";
      case "16":
        return "America/Argentina/San_Luis";
      case "17":
        return "America/Argentina/Salta";
      case "18":
        return "America/Argentina/San_Juan";
      case "19":
        return "America/Argentina/San_Luis";
      case "20":
        return "America/Argentina/Rio_Gallegos";
      case "21":
        return "America/Argentina/Cordoba";
      case "22":
        return "America/Argentina/Catamarca";
      case "23":
        return "America/Argentina/Ushuaia";
      case "24":
        return "America/Argentina/Tucuman";
      default:
        return "America/Argentina";
    }
  }
}
